import React from "react";

export default function Allgall() {
  return (
    <>
      <div className="wrapper">
        <div className="top-div">
          <div className="allSelect">갤러리 전체보기</div>
        </div>
        <div className="mid-div">
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
            <div>OOO갤러리</div>
        </div>
      </div>
    </>
  );
}
